### ISSUE TITLE
5 second pause when running

### ISSUE THREAD

**Issue by rippo** [zopanix/docker_casperjs#1]
thanks for this image it works great, however I am finding that there is delay of 5 or so secs to call casper.start 

If I run locally on my dev box

`casperjs test ./tests/logged.out.js --baseUrl=http://test.com:62726`

The script takes around 2secs 

`PASS 35 tests executed in 2.015s, 35 passed, 0 failed, 0 dubious, 0 skipped.`

If I run this via docker

`docker run -v d:/tests:/data zopanix/casperjs test logged.out.js --baseUrl=http://test.com:62726`

It starts instantly and shows the following

```
Logged out pages
PASS Logged out pages (35 tests)
```

however there is now a pause for around 5 secs and then the tests run

`PASS 35 tests executed in 7.376s, 35 passed, 0 failed, 0 dubious, 0 skipped.`

Therefore something is delaying the call to `casper.start` by around 5 secs. Have you seen this behaviour and is there anything I can do to speed it up?

the first few lines of my casper script is

```
casper.test.begin('Logged out pages', 35, function (test) {
    casper.start(casper.cli.options.baseUrl + "", function () {

```

**Comment by rippo** [comment]
Have added a simple test script that shows this behaviour

```
casper.test.begin('Testing Google', 1, function () {

    casper.start("https://www.google.co.uk", function () {
        casper.test.assertTextExists("Google" );
    });

    casper.run(function () {
        casper.test.done();
    });
});

```    

run from command 

`casperjs test  d:\_tmp\google.js`

run using docker

`docker run -v d:/_tmp:/data zopanix/casperjs test google.js`

**Comment by zopanix** [comment]
Hey, sorry didn't see you comments. I don't do anything special to delay the scripts...
It could be that the is some init done while running it in docker and that is already done on your machine during boot.

**Comment by rippo** [comment]
No worries, I assume you see this behaviour as well

**Comment by zopanix** [comment]
Weel not really.  The script I launched with campers were taking about 10min so I didn't see the 5sec delay. I am going to close this issue since there is not much to do.
